providers = ["node"]
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1727136237'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
PORT = '8000'
FLAG_PROMOTE_EE = 'false'

[phases.setup]
nixPkgs = ['bun']

[phases.install]
dependsOn = ['setup']
# Set up GitHub packages authentication using environment variable
cmds = [
    'echo "@paulgeorge35:registry=https://npm.pkg.github.com" >> /root/.npmrc',
    'echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> /root/.npmrc',
    'bun install --frozen-lockfile'
]
cacheDirectories = ['/root/.bun']

[phases.build]
dependsOn = ['install']
cmds = [
    'bun run generate',
    'bun run build'
]
cacheDirectories = ['node_modules/.cache']

[start]
cmd = 'bun run apps/api/dist/index.js' 