/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as PublicImport } from './routes/_public'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as AdminFeedbackImport } from './routes/admin/feedback'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexImport } from './routes/admin/settings/index'
import { Route as AdminRoadmapIndexImport } from './routes/admin/roadmap/index'
import { Route as AdminChangelogIndexImport } from './routes/admin/changelog/index'
import { Route as PublicBoardSlugIndexImport } from './routes/_public/$boardSlug/index'
import { Route as AdminFeedbackBoardSlugImport } from './routes/admin/feedback/$boardSlug'
import { Route as PublicBoardSlugFeedbackSlugIndexImport } from './routes/_public/$boardSlug/$feedbackSlug/index'
import { Route as AdminFeedbackBoardSlugFeedbackSlugImport } from './routes/admin/feedback/$boardSlug/$feedbackSlug'
import { Route as PublicBoardSlugFeedbackSlugVotersImport } from './routes/_public/$boardSlug/$feedbackSlug/voters'
import { Route as PublicBoardSlugFeedbackSlugEditHistoryImport } from './routes/_public/$boardSlug/$feedbackSlug/edit-history'
import { Route as PublicBoardSlugFeedbackSlugEditImport } from './routes/_public/$boardSlug/$feedbackSlug/edit'
import { Route as AdminFeedbackBoardSlugFeedbackSlugIndexImport } from './routes/admin/feedback/$boardSlug/$feedbackSlug/index'
import { Route as AdminFeedbackBoardSlugFeedbackSlugVotersImport } from './routes/admin/feedback/$boardSlug/$feedbackSlug/voters'
import { Route as AdminFeedbackBoardSlugFeedbackSlugEditHistoryImport } from './routes/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
import { Route as AdminFeedbackBoardSlugFeedbackSlugEditImport } from './routes/admin/feedback/$boardSlug/$feedbackSlug/edit'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const AdminFeedbackRoute = AdminFeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSettingsIndexRoute = AdminSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRoadmapIndexRoute = AdminRoadmapIndexImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminChangelogIndexRoute = AdminChangelogIndexImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => AdminRoute,
} as any)

const PublicBoardSlugIndexRoute = PublicBoardSlugIndexImport.update({
  id: '/$boardSlug/',
  path: '/$boardSlug/',
  getParentRoute: () => PublicRoute,
} as any)

const AdminFeedbackBoardSlugRoute = AdminFeedbackBoardSlugImport.update({
  id: '/$boardSlug',
  path: '/$boardSlug',
  getParentRoute: () => AdminFeedbackRoute,
} as any)

const PublicBoardSlugFeedbackSlugIndexRoute =
  PublicBoardSlugFeedbackSlugIndexImport.update({
    id: '/$boardSlug/$feedbackSlug/',
    path: '/$boardSlug/$feedbackSlug/',
    getParentRoute: () => PublicRoute,
  } as any)

const AdminFeedbackBoardSlugFeedbackSlugRoute =
  AdminFeedbackBoardSlugFeedbackSlugImport.update({
    id: '/$feedbackSlug',
    path: '/$feedbackSlug',
    getParentRoute: () => AdminFeedbackBoardSlugRoute,
  } as any)

const PublicBoardSlugFeedbackSlugVotersRoute =
  PublicBoardSlugFeedbackSlugVotersImport.update({
    id: '/$boardSlug/$feedbackSlug/voters',
    path: '/$boardSlug/$feedbackSlug/voters',
    getParentRoute: () => PublicRoute,
  } as any)

const PublicBoardSlugFeedbackSlugEditHistoryRoute =
  PublicBoardSlugFeedbackSlugEditHistoryImport.update({
    id: '/$boardSlug/$feedbackSlug/edit-history',
    path: '/$boardSlug/$feedbackSlug/edit-history',
    getParentRoute: () => PublicRoute,
  } as any)

const PublicBoardSlugFeedbackSlugEditRoute =
  PublicBoardSlugFeedbackSlugEditImport.update({
    id: '/$boardSlug/$feedbackSlug/edit',
    path: '/$boardSlug/$feedbackSlug/edit',
    getParentRoute: () => PublicRoute,
  } as any)

const AdminFeedbackBoardSlugFeedbackSlugIndexRoute =
  AdminFeedbackBoardSlugFeedbackSlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminFeedbackBoardSlugFeedbackSlugRoute,
  } as any)

const AdminFeedbackBoardSlugFeedbackSlugVotersRoute =
  AdminFeedbackBoardSlugFeedbackSlugVotersImport.update({
    id: '/voters',
    path: '/voters',
    getParentRoute: () => AdminFeedbackBoardSlugFeedbackSlugRoute,
  } as any)

const AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute =
  AdminFeedbackBoardSlugFeedbackSlugEditHistoryImport.update({
    id: '/edit-history',
    path: '/edit-history',
    getParentRoute: () => AdminFeedbackBoardSlugFeedbackSlugRoute,
  } as any)

const AdminFeedbackBoardSlugFeedbackSlugEditRoute =
  AdminFeedbackBoardSlugFeedbackSlugEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminFeedbackBoardSlugFeedbackSlugRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackImport
      parentRoute: typeof AdminImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/feedback/$boardSlug': {
      id: '/admin/feedback/$boardSlug'
      path: '/$boardSlug'
      fullPath: '/admin/feedback/$boardSlug'
      preLoaderRoute: typeof AdminFeedbackBoardSlugImport
      parentRoute: typeof AdminFeedbackImport
    }
    '/_public/$boardSlug/': {
      id: '/_public/$boardSlug/'
      path: '/$boardSlug'
      fullPath: '/$boardSlug'
      preLoaderRoute: typeof PublicBoardSlugIndexImport
      parentRoute: typeof PublicImport
    }
    '/admin/changelog/': {
      id: '/admin/changelog/'
      path: '/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof AdminChangelogIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/roadmap/': {
      id: '/admin/roadmap/'
      path: '/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminImport
    }
    '/_public/$boardSlug/$feedbackSlug/edit': {
      id: '/_public/$boardSlug/$feedbackSlug/edit'
      path: '/$boardSlug/$feedbackSlug/edit'
      fullPath: '/$boardSlug/$feedbackSlug/edit'
      preLoaderRoute: typeof PublicBoardSlugFeedbackSlugEditImport
      parentRoute: typeof PublicImport
    }
    '/_public/$boardSlug/$feedbackSlug/edit-history': {
      id: '/_public/$boardSlug/$feedbackSlug/edit-history'
      path: '/$boardSlug/$feedbackSlug/edit-history'
      fullPath: '/$boardSlug/$feedbackSlug/edit-history'
      preLoaderRoute: typeof PublicBoardSlugFeedbackSlugEditHistoryImport
      parentRoute: typeof PublicImport
    }
    '/_public/$boardSlug/$feedbackSlug/voters': {
      id: '/_public/$boardSlug/$feedbackSlug/voters'
      path: '/$boardSlug/$feedbackSlug/voters'
      fullPath: '/$boardSlug/$feedbackSlug/voters'
      preLoaderRoute: typeof PublicBoardSlugFeedbackSlugVotersImport
      parentRoute: typeof PublicImport
    }
    '/admin/feedback/$boardSlug/$feedbackSlug': {
      id: '/admin/feedback/$boardSlug/$feedbackSlug'
      path: '/$feedbackSlug'
      fullPath: '/admin/feedback/$boardSlug/$feedbackSlug'
      preLoaderRoute: typeof AdminFeedbackBoardSlugFeedbackSlugImport
      parentRoute: typeof AdminFeedbackBoardSlugImport
    }
    '/_public/$boardSlug/$feedbackSlug/': {
      id: '/_public/$boardSlug/$feedbackSlug/'
      path: '/$boardSlug/$feedbackSlug'
      fullPath: '/$boardSlug/$feedbackSlug'
      preLoaderRoute: typeof PublicBoardSlugFeedbackSlugIndexImport
      parentRoute: typeof PublicImport
    }
    '/admin/feedback/$boardSlug/$feedbackSlug/edit': {
      id: '/admin/feedback/$boardSlug/$feedbackSlug/edit'
      path: '/edit'
      fullPath: '/admin/feedback/$boardSlug/$feedbackSlug/edit'
      preLoaderRoute: typeof AdminFeedbackBoardSlugFeedbackSlugEditImport
      parentRoute: typeof AdminFeedbackBoardSlugFeedbackSlugImport
    }
    '/admin/feedback/$boardSlug/$feedbackSlug/edit-history': {
      id: '/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
      path: '/edit-history'
      fullPath: '/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
      preLoaderRoute: typeof AdminFeedbackBoardSlugFeedbackSlugEditHistoryImport
      parentRoute: typeof AdminFeedbackBoardSlugFeedbackSlugImport
    }
    '/admin/feedback/$boardSlug/$feedbackSlug/voters': {
      id: '/admin/feedback/$boardSlug/$feedbackSlug/voters'
      path: '/voters'
      fullPath: '/admin/feedback/$boardSlug/$feedbackSlug/voters'
      preLoaderRoute: typeof AdminFeedbackBoardSlugFeedbackSlugVotersImport
      parentRoute: typeof AdminFeedbackBoardSlugFeedbackSlugImport
    }
    '/admin/feedback/$boardSlug/$feedbackSlug/': {
      id: '/admin/feedback/$boardSlug/$feedbackSlug/'
      path: '/'
      fullPath: '/admin/feedback/$boardSlug/$feedbackSlug/'
      preLoaderRoute: typeof AdminFeedbackBoardSlugFeedbackSlugIndexImport
      parentRoute: typeof AdminFeedbackBoardSlugFeedbackSlugImport
    }
  }
}

// Create and export the route tree

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBoardSlugIndexRoute: typeof PublicBoardSlugIndexRoute
  PublicBoardSlugFeedbackSlugEditRoute: typeof PublicBoardSlugFeedbackSlugEditRoute
  PublicBoardSlugFeedbackSlugEditHistoryRoute: typeof PublicBoardSlugFeedbackSlugEditHistoryRoute
  PublicBoardSlugFeedbackSlugVotersRoute: typeof PublicBoardSlugFeedbackSlugVotersRoute
  PublicBoardSlugFeedbackSlugIndexRoute: typeof PublicBoardSlugFeedbackSlugIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBoardSlugIndexRoute: PublicBoardSlugIndexRoute,
  PublicBoardSlugFeedbackSlugEditRoute: PublicBoardSlugFeedbackSlugEditRoute,
  PublicBoardSlugFeedbackSlugEditHistoryRoute:
    PublicBoardSlugFeedbackSlugEditHistoryRoute,
  PublicBoardSlugFeedbackSlugVotersRoute:
    PublicBoardSlugFeedbackSlugVotersRoute,
  PublicBoardSlugFeedbackSlugIndexRoute: PublicBoardSlugFeedbackSlugIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminFeedbackBoardSlugFeedbackSlugRouteChildren {
  AdminFeedbackBoardSlugFeedbackSlugEditRoute: typeof AdminFeedbackBoardSlugFeedbackSlugEditRoute
  AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute: typeof AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute
  AdminFeedbackBoardSlugFeedbackSlugVotersRoute: typeof AdminFeedbackBoardSlugFeedbackSlugVotersRoute
  AdminFeedbackBoardSlugFeedbackSlugIndexRoute: typeof AdminFeedbackBoardSlugFeedbackSlugIndexRoute
}

const AdminFeedbackBoardSlugFeedbackSlugRouteChildren: AdminFeedbackBoardSlugFeedbackSlugRouteChildren =
  {
    AdminFeedbackBoardSlugFeedbackSlugEditRoute:
      AdminFeedbackBoardSlugFeedbackSlugEditRoute,
    AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute:
      AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute,
    AdminFeedbackBoardSlugFeedbackSlugVotersRoute:
      AdminFeedbackBoardSlugFeedbackSlugVotersRoute,
    AdminFeedbackBoardSlugFeedbackSlugIndexRoute:
      AdminFeedbackBoardSlugFeedbackSlugIndexRoute,
  }

const AdminFeedbackBoardSlugFeedbackSlugRouteWithChildren =
  AdminFeedbackBoardSlugFeedbackSlugRoute._addFileChildren(
    AdminFeedbackBoardSlugFeedbackSlugRouteChildren,
  )

interface AdminFeedbackBoardSlugRouteChildren {
  AdminFeedbackBoardSlugFeedbackSlugRoute: typeof AdminFeedbackBoardSlugFeedbackSlugRouteWithChildren
}

const AdminFeedbackBoardSlugRouteChildren: AdminFeedbackBoardSlugRouteChildren =
  {
    AdminFeedbackBoardSlugFeedbackSlugRoute:
      AdminFeedbackBoardSlugFeedbackSlugRouteWithChildren,
  }

const AdminFeedbackBoardSlugRouteWithChildren =
  AdminFeedbackBoardSlugRoute._addFileChildren(
    AdminFeedbackBoardSlugRouteChildren,
  )

interface AdminFeedbackRouteChildren {
  AdminFeedbackBoardSlugRoute: typeof AdminFeedbackBoardSlugRouteWithChildren
}

const AdminFeedbackRouteChildren: AdminFeedbackRouteChildren = {
  AdminFeedbackBoardSlugRoute: AdminFeedbackBoardSlugRouteWithChildren,
}

const AdminFeedbackRouteWithChildren = AdminFeedbackRoute._addFileChildren(
  AdminFeedbackRouteChildren,
)

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChangelogIndexRoute: typeof AdminChangelogIndexRoute
  AdminRoadmapIndexRoute: typeof AdminRoadmapIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminChangelogIndexRoute: AdminChangelogIndexRoute,
  AdminRoadmapIndexRoute: AdminRoadmapIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/feedback/$boardSlug': typeof AdminFeedbackBoardSlugRouteWithChildren
  '/$boardSlug': typeof PublicBoardSlugIndexRoute
  '/admin/changelog': typeof AdminChangelogIndexRoute
  '/admin/roadmap': typeof AdminRoadmapIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/$boardSlug/$feedbackSlug/edit': typeof PublicBoardSlugFeedbackSlugEditRoute
  '/$boardSlug/$feedbackSlug/edit-history': typeof PublicBoardSlugFeedbackSlugEditHistoryRoute
  '/$boardSlug/$feedbackSlug/voters': typeof PublicBoardSlugFeedbackSlugVotersRoute
  '/admin/feedback/$boardSlug/$feedbackSlug': typeof AdminFeedbackBoardSlugFeedbackSlugRouteWithChildren
  '/$boardSlug/$feedbackSlug': typeof PublicBoardSlugFeedbackSlugIndexRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit': typeof AdminFeedbackBoardSlugFeedbackSlugEditRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit-history': typeof AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/voters': typeof AdminFeedbackBoardSlugFeedbackSlugVotersRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/': typeof AdminFeedbackBoardSlugFeedbackSlugIndexRoute
}

export interface FileRoutesByTo {
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/feedback/$boardSlug': typeof AdminFeedbackBoardSlugRouteWithChildren
  '/$boardSlug': typeof PublicBoardSlugIndexRoute
  '/admin/changelog': typeof AdminChangelogIndexRoute
  '/admin/roadmap': typeof AdminRoadmapIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/$boardSlug/$feedbackSlug/edit': typeof PublicBoardSlugFeedbackSlugEditRoute
  '/$boardSlug/$feedbackSlug/edit-history': typeof PublicBoardSlugFeedbackSlugEditHistoryRoute
  '/$boardSlug/$feedbackSlug/voters': typeof PublicBoardSlugFeedbackSlugVotersRoute
  '/$boardSlug/$feedbackSlug': typeof PublicBoardSlugFeedbackSlugIndexRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit': typeof AdminFeedbackBoardSlugFeedbackSlugEditRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit-history': typeof AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/voters': typeof AdminFeedbackBoardSlugFeedbackSlugVotersRoute
  '/admin/feedback/$boardSlug/$feedbackSlug': typeof AdminFeedbackBoardSlugFeedbackSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/feedback/$boardSlug': typeof AdminFeedbackBoardSlugRouteWithChildren
  '/_public/$boardSlug/': typeof PublicBoardSlugIndexRoute
  '/admin/changelog/': typeof AdminChangelogIndexRoute
  '/admin/roadmap/': typeof AdminRoadmapIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_public/$boardSlug/$feedbackSlug/edit': typeof PublicBoardSlugFeedbackSlugEditRoute
  '/_public/$boardSlug/$feedbackSlug/edit-history': typeof PublicBoardSlugFeedbackSlugEditHistoryRoute
  '/_public/$boardSlug/$feedbackSlug/voters': typeof PublicBoardSlugFeedbackSlugVotersRoute
  '/admin/feedback/$boardSlug/$feedbackSlug': typeof AdminFeedbackBoardSlugFeedbackSlugRouteWithChildren
  '/_public/$boardSlug/$feedbackSlug/': typeof PublicBoardSlugFeedbackSlugIndexRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit': typeof AdminFeedbackBoardSlugFeedbackSlugEditRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/edit-history': typeof AdminFeedbackBoardSlugFeedbackSlugEditHistoryRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/voters': typeof AdminFeedbackBoardSlugFeedbackSlugVotersRoute
  '/admin/feedback/$boardSlug/$feedbackSlug/': typeof AdminFeedbackBoardSlugFeedbackSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/admin/feedback'
    | '/'
    | '/admin/'
    | '/admin/feedback/$boardSlug'
    | '/$boardSlug'
    | '/admin/changelog'
    | '/admin/roadmap'
    | '/admin/settings'
    | '/admin/users'
    | '/$boardSlug/$feedbackSlug/edit'
    | '/$boardSlug/$feedbackSlug/edit-history'
    | '/$boardSlug/$feedbackSlug/voters'
    | '/admin/feedback/$boardSlug/$feedbackSlug'
    | '/$boardSlug/$feedbackSlug'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
    | '/admin/feedback/$boardSlug/$feedbackSlug/voters'
    | '/admin/feedback/$boardSlug/$feedbackSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/feedback'
    | '/'
    | '/admin'
    | '/admin/feedback/$boardSlug'
    | '/$boardSlug'
    | '/admin/changelog'
    | '/admin/roadmap'
    | '/admin/settings'
    | '/admin/users'
    | '/$boardSlug/$feedbackSlug/edit'
    | '/$boardSlug/$feedbackSlug/edit-history'
    | '/$boardSlug/$feedbackSlug/voters'
    | '/$boardSlug/$feedbackSlug'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
    | '/admin/feedback/$boardSlug/$feedbackSlug/voters'
    | '/admin/feedback/$boardSlug/$feedbackSlug'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/admin/feedback'
    | '/_public/'
    | '/admin/'
    | '/admin/feedback/$boardSlug'
    | '/_public/$boardSlug/'
    | '/admin/changelog/'
    | '/admin/roadmap/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/_public/$boardSlug/$feedbackSlug/edit'
    | '/_public/$boardSlug/$feedbackSlug/edit-history'
    | '/_public/$boardSlug/$feedbackSlug/voters'
    | '/admin/feedback/$boardSlug/$feedbackSlug'
    | '/_public/$boardSlug/$feedbackSlug/'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit'
    | '/admin/feedback/$boardSlug/$feedbackSlug/edit-history'
    | '/admin/feedback/$boardSlug/$feedbackSlug/voters'
    | '/admin/feedback/$boardSlug/$feedbackSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public",
        "/admin"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/",
        "/_public/$boardSlug/",
        "/_public/$boardSlug/$feedbackSlug/edit",
        "/_public/$boardSlug/$feedbackSlug/edit-history",
        "/_public/$boardSlug/$feedbackSlug/voters",
        "/_public/$boardSlug/$feedbackSlug/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/feedback",
        "/admin/",
        "/admin/changelog/",
        "/admin/roadmap/",
        "/admin/settings/",
        "/admin/users/"
      ]
    },
    "/admin/feedback": {
      "filePath": "admin/feedback.tsx",
      "parent": "/admin",
      "children": [
        "/admin/feedback/$boardSlug"
      ]
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/feedback/$boardSlug": {
      "filePath": "admin/feedback/$boardSlug.tsx",
      "parent": "/admin/feedback",
      "children": [
        "/admin/feedback/$boardSlug/$feedbackSlug"
      ]
    },
    "/_public/$boardSlug/": {
      "filePath": "_public/$boardSlug/index.tsx",
      "parent": "/_public"
    },
    "/admin/changelog/": {
      "filePath": "admin/changelog/index.tsx",
      "parent": "/admin"
    },
    "/admin/roadmap/": {
      "filePath": "admin/roadmap/index.tsx",
      "parent": "/admin"
    },
    "/admin/settings/": {
      "filePath": "admin/settings/index.tsx",
      "parent": "/admin"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/_public/$boardSlug/$feedbackSlug/edit": {
      "filePath": "_public/$boardSlug/$feedbackSlug/edit.tsx",
      "parent": "/_public"
    },
    "/_public/$boardSlug/$feedbackSlug/edit-history": {
      "filePath": "_public/$boardSlug/$feedbackSlug/edit-history.tsx",
      "parent": "/_public"
    },
    "/_public/$boardSlug/$feedbackSlug/voters": {
      "filePath": "_public/$boardSlug/$feedbackSlug/voters.tsx",
      "parent": "/_public"
    },
    "/admin/feedback/$boardSlug/$feedbackSlug": {
      "filePath": "admin/feedback/$boardSlug/$feedbackSlug.tsx",
      "parent": "/admin/feedback/$boardSlug",
      "children": [
        "/admin/feedback/$boardSlug/$feedbackSlug/edit",
        "/admin/feedback/$boardSlug/$feedbackSlug/edit-history",
        "/admin/feedback/$boardSlug/$feedbackSlug/voters",
        "/admin/feedback/$boardSlug/$feedbackSlug/"
      ]
    },
    "/_public/$boardSlug/$feedbackSlug/": {
      "filePath": "_public/$boardSlug/$feedbackSlug/index.tsx",
      "parent": "/_public"
    },
    "/admin/feedback/$boardSlug/$feedbackSlug/edit": {
      "filePath": "admin/feedback/$boardSlug/$feedbackSlug/edit.tsx",
      "parent": "/admin/feedback/$boardSlug/$feedbackSlug"
    },
    "/admin/feedback/$boardSlug/$feedbackSlug/edit-history": {
      "filePath": "admin/feedback/$boardSlug/$feedbackSlug/edit-history.tsx",
      "parent": "/admin/feedback/$boardSlug/$feedbackSlug"
    },
    "/admin/feedback/$boardSlug/$feedbackSlug/voters": {
      "filePath": "admin/feedback/$boardSlug/$feedbackSlug/voters.tsx",
      "parent": "/admin/feedback/$boardSlug/$feedbackSlug"
    },
    "/admin/feedback/$boardSlug/$feedbackSlug/": {
      "filePath": "admin/feedback/$boardSlug/$feedbackSlug/index.tsx",
      "parent": "/admin/feedback/$boardSlug/$feedbackSlug"
    }
  }
}
ROUTE_MANIFEST_END */
